=== omshejul/jsonforms-react-seed/src/pages/StoreConversation/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "goal_name": {
      "type": "string"
    },
    "client_id": {
      "type": "string"
    },
    "language": {
      "type": "string"
    },
    "message": {
      "type": "string"
    },
    "question": {
      "type": "string"
    },
    "switch_language": {
      "type": "boolean"
    },
    "slots": {
      "type": "object",
      "properties": {
        "greetings": {
          "$ref": "#/definitions/slot"
        },
        "renewal": {
          "$ref": "#/definitions/slot"
        },
        "renewal_due_soon": {
          "$ref": "#/definitions/slot"
        },
        "renewal_options": {
          "$ref": "#/definitions/slot"
        },
        "contact_preferences": {
          "$ref": "#/definitions/slot"
        },
        "confirm_schedule": {
          "$ref": "#/definitions/slot"
        }
      }
    }
  },
  "definitions": {
    "slot": {
      "type": "object",
      "properties": {
        "question": {
          "type": "string"
        },
        "response": {
          "type": "string"
        },
        "required": {
          "type": "boolean"
        },
        "datatype": {
          "type": "string"
        },
        "required_format": {
          "type": "string"
        },
        "exhaustive": {
          "type": "boolean",
          "default": false
        },
        "exhaustive_data": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "sample": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "next_node": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "conditional_closing": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "reward": {
          "type": "number"
        },
        "error_message": {
          "type": "string"
        }
      },
      "required": ["question"]
    }
  }
}

=== omshejul/jsonforms-react-seed/src/pages/StoreConversation/initialJsonData.json
{
  "goal_name": "HDFC ERGO",
  "client_id": "22",
  "language" : "en",
  "message": "Thank you for being a valuable customer. Have a great day!",
  "question" : "I want to talk to HDFC",
  "switch_language": true ,
  "slots": {
    "greetings": {
      "question": "Dear Customer, This is HDFC Ergo calling.  I'm your virtual assistant. We hope you're doing well.",
      "response": "",
      "required": false,
      "datatype": "string",
      "required_format": "",
      "features": [],
      "ner": [],
      "ner_ngram": [],
      "span": [],
      "trigger_words": [],
      "sample": ["yes", "no"],
      "conditions": [],
      "next_node": ["renewal"],
      "conditional_closing": ["yes"],
      "reward": 0,
      "error_message": ""
    },
    "renewal": {
      "question": "We're calling to remind you that your motor insurance policy for your vehicle is due for renewal soon.",
      "response": "",
      "required": false,
      "datatype": "string",
      "required_format": "",
      "features": [],
      "ner": [],
      "ner_ngram": [],
      "span": [],
      "trigger_words": [],
      "sample": ["yes", "no"],
      "conditions": [],
      "next_node": ["renewal_due_soon"],
      "conditional_closing": ["yes"],
      "reward": 0,
      "error_message": ""
    },
    "renewal_due_soon": {
      "question": "To continue enjoying uninterrupted coverage, we recommend renewing your policy before the expiration date.",
      "response": "",
      "required": false,
      "datatype": "string",
      "required_format": "",
      "features": [],
      "ner": [],
      "ner_ngram": [],
      "span": [],
      "trigger_words": [],
      "sample": ["yes", "no"],
      "conditions": [],
      "next_node": ["renewal_options"],
      "conditional_closing": ["yes"],
      "reward": 0,
      "error_message": ""
    },
    "renewal_options": {
      "question": "Would you like more information about the renewal options available for your motor insurance policy ? please say yes no",
      "response": "",
      "required": false,
      "datatype": "string",
      "exhaustive" : true,
      "exhaustive_data" : ["yes","no"],
      "ner_ngram": [],
      "span": [],
      "trigger_words": [],
      "sample": ["yes", "no"],
      "conditions": [],
      "next_node": ["contact_preferences"],
      "conditional_closing": ["yes"],
      "reward": 0,
      "error_message": ""
    },
    "contact_preferences": {
      "question": "How would you prefer to receive further communication regarding your policy renewal?",
      "response": "",
      "required": false,
      "datatype": "string",
      "required_format": "",
      "exhaustive" : true,
      "exhaustive_data" : ["email", "SMS", "phone call", "whatsapp"],
      "ner_ngram": [],
      "span": [],
      "trigger_words": [],
      "sample": ["email", "SMS", "phone call", "whatsapp"],
      "conditions": [],
      "next_node": ["confirm_schedule"],
      "conditional_closing": ["yes"],
      "reward": 0,
      "error_message": ""
    },
    "confirm_schedule": {
      "question": "Great! I've noted your preference. Thank you for considering a policy review with HDFC Ergo. we will call you shortly",
      "response": "",
      "required": false,
      "datatype": "string",
      "required_format": "",
      "features": [],
      "ner": [],
      "ner_ngram": [],
      "span": [],
      "trigger_words": [],
      "sample": ["thank you"],
      "conditions": [
      ],
      "conditional_closing": ["yes"],
      "reward": 0,
      "error_message": ""
    }
    }
  }
