=== omshejul/jsonforms-react-seed/src/pages/DialogueManager2/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "goal_name": { "type": "string" },
    "client_id": { "type": "string" },
    "language": {
      "type": "string",
      "oneOf": [
        { "title": "Assamese অসমীয়া", "const": "as" },
        { "title": "Bengali বাংলা", "const": "bn" },
        { "title": "English", "const": "en" },
        { "title": "Gujarati ગુજરાતી", "const": "gu" },
        { "title": "Hindi हिंदी", "const": "hi" },
        { "title": "Kannada ಕನ್ನಡ", "const": "kn" },
        { "title": "Maithili मैथिली", "const": "mai" },
        { "title": "Malayalam മലയാളം", "const": "ml" },
        { "title": "Marathi मराठी", "const": "mr" },
        { "title": "Meitei মৈতৈলোন্", "const": "mni" },
        { "title": "Odia ଓଡ଼ିଆ", "const": "or" },
        { "title": "Punjabi ਪੰਜਾਬੀ", "const": "pa" },
        { "title": "Sanskrit संस्कृतम्", "const": "sa" },
        { "title": "Tamil தமிழ்", "const": "ta" },
        { "title": "Telugu తెలుగు", "const": "te" },
        { "title": "Urdu اُردُو", "const": "ur" }
      ]
    },
    "source_language": {
      "type": "string",
      "oneOf": [
        { "title": "", "const": "" },
        { "title": "Assamese অসমীয়া", "const": "as" },
        { "title": "Bengali বাংলা", "const": "bn" },
        { "title": "English", "const": "en" },
        { "title": "Gujarati ગુજરાતી", "const": "gu" },
        { "title": "Hindi हिंदी", "const": "hi" },
        { "title": "Kannada ಕನ್ನಡ", "const": "kn" },
        { "title": "Maithili मैथिली", "const": "mai" },
        { "title": "Malayalam മലയാളം", "const": "ml" },
        { "title": "Marathi मराठी", "const": "mr" },
        { "title": "Meitei মৈতৈলোন্", "const": "mni" },
        { "title": "Odia ଓଡ଼ିଆ", "const": "or" },
        { "title": "Punjabi ਪੰਜਾਬੀ", "const": "pa" },
        { "title": "Sanskrit संस्कृतम्", "const": "sa" },
        { "title": "Tamil தமிழ்", "const": "ta" },
        { "title": "Telugu తెలుగు", "const": "te" },
        { "title": "Urdu اُردُو", "const": "ur" }
      ]
    },
    "traget_language": {
      "type": "string",
      "oneOf": [
        { "title": "", "const": "" },
        { "title": "Assamese অসমীয়া", "const": "as" },
        { "title": "Bengali বাংলা", "const": "bn" },
        { "title": "English", "const": "en" },
        { "title": "Gujarati ગુજરાતી", "const": "gu" },
        { "title": "Hindi हिंदी", "const": "hi" },
        { "title": "Kannada ಕನ್ನಡ", "const": "kn" },
        { "title": "Maithili मैथिली", "const": "mai" },
        { "title": "Malayalam മലയാളം", "const": "ml" },
        { "title": "Marathi मराठी", "const": "mr" },
        { "title": "Meitei মৈতৈলোন্", "const": "mni" },
        { "title": "Odia ଓଡ଼ିଆ", "const": "or" },
        { "title": "Punjabi ਪੰਜਾਬੀ", "const": "pa" },
        { "title": "Sanskrit संस्कृतम्", "const": "sa" },
        { "title": "Tamil தமிழ்", "const": "ta" },
        { "title": "Telugu తెలుగు", "const": "te" },
        { "title": "Urdu اُردُو", "const": "ur" }
      ]
    },
    "translated_output": { "type": "string" },
    "message": { "type": "string" },
    "question": { "type": "string" },
    "switch_language": { "type": "boolean" },

    "slots": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "greetings",
              "service-segment",
              "check-complaint-status-1",
              "check-complaint-status-2",
              "customer-number",
              "customer-name",
              "customer-pincode",
              "customer-address",
              "product-id",
              "problem-id",
              "serial-number-method",
              "scan-serial-number",
              "enter-serial-number",
              "purchase-date",
              "complaint-registration-confirm",
              "complaint-registration-success",
              "upload-bill",
              "upload-warranty",
              "product-registration-confirm",
              "product-registration-success",
              "query-1",
              "query-2",
              "sales-segment",
              "sales-products-1",
              "sales-products-2",
              "sales-products-3",
              "final-node",
              "thanks"
            ]
          },
          "data": {
            "$ref": "#/$defs/commonFields"
          }
        }
      }
    }
  },
  "$defs": {
    "commonFields": {
      "type": "object",
      "properties": {
        "question": {
          "type": "string",
          "description": "A prompt or question presented to the user."
        },
        "choices": {
          "type": "boolean",
          "description": "Indicates if there are choices available for the user."
        },
        "bot_message": {
          "type": "string",
          "default": "test",

          "description": "A message from the bot, typically the question to display."
        },
        "response": {
          "type": "string",
          "default": "test"
        },
        "pre_condition": {
          "type": "object",
          "properties": {
            "condition_type": {
              "type": "string",
              "enum": ["exact", "python", "polars", "similarity"],
              "description": "The type of condition to evaluate the input."
            },
            "value_to_check": {
              "type": "string",
              "description": "The variable to be checked, usually user input."
            },
            "condition": {
              "type": "string",
              "description": "The specific condition to match against the input."
            },
            "error_message": {
              "type": "string",
              "description": "Message displayed on error."
            }
          }
        },
        "apis": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": { "type": "string" },
              "endpoint": { "type": "string" },
              "output": { "type": "string" },
              "method": {
                "type": "string",
                "enum": ["GET", "POST", "PUT", "DELETE"]
              },
              "params": {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "key": { "type": "string" },
                    "value": { "type": "string" }
                  },
                  "required": ["key", "value"]
                }
              },
              "error_message": { "type": "string" }
            },
            "required": ["name", "endpoint", "method"]
          }
        },
        "functions": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string",
                "description": "The name of the function, it will be used ad the key in the functions dictionary."
              },
              "input": {
                "type": "array",
                "items": {
                  "type": "string",
                  "description": "References to data outputs from APIs"
                }
              },
              "output": {
                "type": "array",
                "items": {
                  "type": "string",
                  "description": "Names of the outputs this function produces"
                }
              },
              "description": {
                "type": "string",
                "description": "A description of what the function does"
              }
            },
            "required": ["name", "input", "output", "description"]
          }
        },
        "next_node": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "condition_type": {
                "type": "string",
                "enum": ["exact", "python", "polars", "similarity"]
              },
              "value_to_check": {
                "type": "string"
              },
              "condition": {
                "type": "string"
              },
              "value_match": {
                "type": "string"
              },
              "next_node": {
                "type": "array",
                "maxItems": 1,
                "items": {
                  "type": "string",
                  "enum": [
                    "greetings",
                    "service-segment",
                    "check-complaint-status-1",
                    "check-complaint-status-2",
                    "customer-number",
                    "customer-name",
                    "customer-pincode",
                    "customer-address",
                    "product-id",
                    "problem-id",
                    "serial-number-method",
                    "scan-serial-number",
                    "enter-serial-number",
                    "purchase-date",
                    "complaint-registration-confirm",
                    "complaint-registration-success",
                    "upload-bill",
                    "upload-warranty",
                    "product-registration-confirm",
                    "product-registration-success",
                    "query-1",
                    "query-2",
                    "sales-segment",
                    "sales-products-1",
                    "sales-products-2",
                    "sales-products-3",
                    "final-node",
                    "thanks"
                  ]
                }
              }
            }
          }
        },
        "execution_order": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "type": {
                "type": "string",
                "enum": ["api", "function"]
              },
              "name": {
                "type": "string",
                "enum": ["None"]
              }
            }
          }
        },
        "error_message": {
          "type": "string",
          "description": "Error message when the selection is invalid."
        }
      }
    }
  }
}

=== omshejul/jsonforms-react-seed/src/pages/DialogueManager2/initialJsonData.json
{
    "goal_name": "eastman",
    "client_id": "22",
    "language": "en",
    "source_language": "en",
    "traget_language": "en",
    "switch_language": true,
    "question": "Hi, Hello, hi, hello, hey, Hey",
    "slots": [
        {
            "response": "",
            "type": "greetings",
            "data": {
                "question": "Welcome to Eastman Auto & Power Limited. Please choose from the following options",
                "choices": true,
                "bot_message": "question",
                "response": "",
                "pre_condition": {
                    "condition_type": "python",
                    "value_to_check": "{user_input}",
                    "condition": "value",
                    "error_message": "Please enter a 10 digit phone number"
                },
                "execution_order": [
                    {
                        "type": "api"
                    }
                ],
                "functions": [
                    {
                        "name": "fnname",
                        "input": [
                            "test"
                        ],
                        "output": [
                            "op"
                        ],
                        "description": "desc"
                    }
                ],
                "next_node": [
                    {
                        "condition_type": "similarity",
                        "value_to_check": "{user_input}",
                        "condition": "(value)",
                        "value_match": "Services",
                        "next_node": [
                            "customer-number"
                        ]
                    }
                ]
            },
            "apis": [
                {
                    "name": "product_detail",
                    "endpoint": " https://jsonplaceholder.typicode.com/posts",
                    "method": "GET",
                    "params": [],
                    "error_message": "",
                    "headers": {
                        "Content-Type": "application/json"
                    },
                    "output": [
                        "op"
                    ]
                }
            ]
        }
    ]
}

=== omshejul/jsonforms-react-seed/src/pages/DialogueManager/initialJsonData.json
{
  "goal_name": "Eastman_bot",
  "client_id": "88",
  "language": "en",
  "message": "",
  "question": "What is the capital of France?",
  "switch_language": true,

  "slots": [
    {
      "form_name": "Form 1",

      "form_data": {
        "question": "What is the capital of France?",
        "bot_message": "question",
        "response": "",
        "choices": false,
        "conditions": {
          "pre_condition": ["user_input.length > 0"],
          "pre_condition": ["Input cannot be empty"],
          "post_condition": "user_input === 'Paris'",
          "post_condition_error": "Wrong answer. The correct answer is Paris."
        },
        "apis": [
          {
            "name": "Some Name",
            "endpoint": "https://httpbin.org/get",
            "method": "GET",
            "params": [
              {
                "key": "param1",
                "value": "value1"
              }
            ],
            "error_message": ""
          }
        ],
        "functions": [
          {
            "name": "GetNumber",
            "input": "data from previous step",
            "output": "processed data",
            "description": "Some Description"
          }
        ],
        "execution_order": [
          {
            "type": "API",
            "name": "Check Input Length",
            "input": "user_input",
            "evaluation_function": "lengthCheck"
          },
          {
            "type": "FUNCTION",
            "name": "Fetch Data"
          }
        ],
        "next_node": [
          {
            "value_to_check": "user_input.startsWith('P')",
            "condition_type": "",
            "value_match": "sales",
            "next_node": "If condition is true, navigate to the next_node node"
          }
        ],
        "closing_message": false,
        "error_message": "err"
      }
    }
  ]
}

=== omshejul/jsonforms-react-seed/src/pages/DialogueManager2/initialJsonData2.json
{
  "goal_name": "eastman",
  "client_id": "88",
  "language": "en",
  "source_language": "en",
  "traget_language": "en",
  "switch_language": true,
  "question": "Hi, Hello, hi, hello, hey, Hey",
  "slots": [
    {
      "response": "",
      "type": "greetings",
      "data": {
        "question": "Welcome to Eastman Auto & Power Limited. Please choose from the following options",
        "choices": true,
        "bot_message": "question",
        "response": "",
        "pre_condition": {
          "condition_type": "python",
          "value_to_check": "{user_input}",
          "condition": "value",
          "error_message": "Please enter a 10 digit phone number"
        },
        "execution_order": [],
        "functions": [],
        "next_node": [
          {
            "condition_type": "similarity",
            "value_to_check": "{user_input}",
            "condition": "(value)",
            "value_match": "Services",
            "next_node": ["service-segment"]
          },
          {
            "condition_type": "similarity",
            "value_to_check": "{user_input}",
            "condition": "(value)",
            "value_match": "Sales",
            "next_node": ["customer-number"]
          }
        ],
        "apis": []
      },
      "apis": []
    },
    {
      "response": "",
      "type": "service-segment",
      "data": {
        "question": "Please choose from the following options",
        "choices": true,
        "bot_message": "question",
        "response": "",
        "pre_condition": {
          "condition_type": "python",
          "value_to_check": "{user_input}",
          "condition": "value",
          "error_message": "Please enter a 10 digit phone number"
        },
        "execution_order": [],
        "functions": [],
        "next_node": [
          {
            "condition_type": "similarity",
            "value_to_check": "{user_input}",
            "condition": "(value)",
            "value_match": "Raise a Complaint",
            "next_node": ["customer-number"]
          },
          {
            "condition_type": "similarity",
            "value_to_check": "{user_input}",
            "condition": "(value)",
            "value_match": "Check Complaints Status",
            "next_node": ["check-complaint-status-1"]
          },
          {
            "condition_type": "similarity",
            "value_to_check": "{user_input}",
            "condition": "(value)",
            "value_match": "Product Registration",
            "next_node": ["customer-number"]
          },
          {
            "condition_type": "similarity",
            "value_to_check": "{user_input}",
            "condition": "(value)",
            "value_match": "Other Query",
            "next_node": ["customer-number"]
          }
        ],
        "apis": []
      },
      "apis": []
    },
    {
      "response": "",
      "type": "check-complaint-status-1",
      "data": {
        "question": "Enter the complaint number:",
        "choices": true,
        "bot_message": "question",
        "response": "",
        "pre_condition": {
          "condition_type": "python",
          "value_to_check": "{user_input}",
          "condition": "(value.isalnum() and len(value) == 19)",
          "error_message": "Please enter the 19 character complaint number."
        },
        "execution_order": [
          {
            "type": "api"
          }
        ],
        "functions": [],
        "next_node": [
          {
            "condition_type": "python",
            "value_to_check": "{user_input}",
            "condition": "(value)",
            "value_match": "",
            "next_node": ["check-complaint-status-2"]
          }
        ],
        "apis": []
      },
      "apis": [
        {
          "name": "complaint_status",
          "endpoint": "https://crm.eaplworld.com/WhatsAPP_API/prd/getComplaint_Status.php",
          "method": "GET",
          "params": [
            {
              "key": "complaint_no",
              "value": "{user_input}"
            }
          ],
          "error_message": "Invalid complaint number. Please try again",
          "headers": {
            "Content-Type": "application/json"
          },
          "output": ["complaint_status_name"]
        }
      ]
    },
    {
      "response": "",
      "type": "check-complaint-status-2",
      "data": {
        "question": "",
        "choices": true,
        "bot_message": "Complaint status for the complaint number {apis.complaint_status.output[0].complaint_no} is {apis.complaint_status.output[0].status}.",
        "response": "",
        "pre_condition": {
          "condition_type": "python",
          "value_to_check": "{user_input}",
          "condition": "(value)",
          "error_message": "Please enter the 19 character complaint number."
        },
        "execution_order": [],
        "functions": [],
        "next_node": [
          {
            "condition_type": "python",
            "value_to_check": "{user_input}",
            "condition": "",
            "value_match": "",
            "next_node": ["final-node"]
          }
        ],
        "apis": []
      },
      "apis": []
    }
  ]
}
